### ISSUE TITLE
rosjava build fails in zeroconf_jmdns_suite:Unspecified

### ISSUE THREAD

**Issue by srinimd2005** [rosjava/zeroconf_jmdns_suite#45]
Hi 
After the recent commit I am experiencing the rosjava build fail in indigo branch stating
Could not find any version that matches org.ros.rosjava_bootstrap:gradle_plugins:[0.3,0.4)
zeroconf_jmdns_suite:unspecified
Could somebody help?

**Comment by adamantivm** [comment]
@srinimd2005 thank you for bringing this up. It was my fault, I will fix it right away and let you know when it's done.

**Comment by adamantivm** [comment]
@srinimd2005 it should be fixed now. Could you please try to update and try again?

**Comment by srinimd2005** [comment]
Thank you for your reply.
I am still getting this error

 What went wrong:
A problem occurred configuring root project 'std_srvs'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not download artifact 'gradle_plugins.jar (org.ros.rosjava_bootstrap:gradle_plugins:0.2.1)'
      > Could not GET 'https://github.com/rosjava/rosjava_mvn_repo/raw/master/org/ros/rosjava_bootstrap/gradle_plugins/0.2.1/gradle_plugins-0.2.1.jar'.
[ 91%]          > github.com: No address associated with hostname

Built target rosgraph_msgs_generate_messages_java_gradle

I am using indigo branch, is the fix is for indigo or Kinetic...

**Comment by srinimd2005** [comment]
Thank you it's working now.

**Comment by adamantivm** [comment]
Great to here, and sorry for the inconvenience.
